class ContactUsLocators:
    FORM = ("ID", "frm_form_1_container")
    FULLNAME_FIELD = ("ID", "field_qh4icy")
    EMAIL_FIELD = ("ID", "field_ocfup1")
    COMPANY_FIELD = ("ID", "field_29yf4d")
    PHONE_FIELD = ("ID", "field_6lruj")
    HELP_FIELD = ("ID", "field_e6lis6")
    TERMS_CHECKBOX= ("ID", "field_1v1zn-0")
    SUBMIT_BUTTON = ("XPATH", "//div[@class='frm_submit']/button")
    SUCCESSFULLY_SUBMITTED = ("XPATH", "//div[@class='frm_message']")
