class ContactUsLocators:
    FORM = ("ID", "frm_form_1_container")
    FULLNAME_FIELD = ("ID", "field_qh4icy")
    EMAIL_FIELD = ("ID", "field_ocfup1")
    COMPANY_FIELD = ("ID", "field_29yf4d")
    PHONE_FIELD = ("ID", "field_6lruj")
    HELP_FIELD = ("ID", "field_e6lis6")
    TERMS_CHECKBOX= ("ID", "field_1v1zn-0")
    SUBMIT_BUTTON = ("XPATH", "//div[@class='frm_submit']/button")
    SUCCESSFULLY_SUBMITTED = ("XPATH", "//div[@class='frm_message']")
    FORM_ERROR_ALERT = ("XPATH", "//div[@class='frm_error_style']")
    INVALID_NAME_MSG = ("ID", "frm_error_field_qh4icy")
    INVALID_EMAIL_MSG = ("ID", "frm_error_field_ocfup1")
    INVALID_COMPANY_MSG = ("ID", "frm_error_field_29yf4d")
    INVALID_PHONE_MSG = ("ID", "frm_error_field_6lruj")
    INVALID_HELP_MSG = ("ID", "frm_error_field_e6lis6")
    INVALID_CHECKBOX_MSG = ("ID", "frm_error_field_1v1zn")