class OpenPositionLocators:
    POSITION_PAGE_TITLE = ("XPATH", "//h1[@class='heading-title']")
    FULL_NAME_FIELD = ("ID", "field_12kml")
    EMAIL_FIELD = ("ID", "field_cgppt")
    PHONE_FIELD = ("ID", "field_xgcz8")
    CITY_COUNTRY_FIELD = ("ID", "field_zdyoa")
    LINKEDIN_FIELD = ("ID", "field_qqeg6")
    ABOUT_YOU_FIELD = ("ID", "field_2l3hb")
    FILE_TO_ATTACH_FIELD = ("ID", "field_lm2r4")
    FILE_ATTACHED_NAME = ("XPATH", "//div[@class='dz-filename']/span")